version: '3.8'
services:
  fastapi:
    container_name: lb_api_01
    restart: unless-stopped
    build:
      context: ./python_backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - domain
      - project_name
      - postgres_server
      - postgres_user
      - postgres_password
      - postgres_db
      - pgadmin_listen_port
      - pgadmin_default_email
      - pgadmin_default_password
 
